$(document).ready(function(){
	$("#fa").click(function(){
		$(".textof").fadeIn();
	});
	$("#ff").click(function(){
		$(".textof").fadeOut();
	});
	$("#ca").click(function(){
		$(".textoc").fadeIn();
	});
	$("#cf").click(function(){
		$(".textoc").fadeOut();
	});
});
